service:
  name: autenticar-ia
  version: mvp-1
  host: 0.0.0.0
  port: 8000
  require_api_key: false   

security:
  api_key_env: IA_API_KEY  

paths:
  workdir: "./data/work"   
  keep_temp: false         

limits:
  max_bytes: 15728640      
  allowed_ext: [".pdf", ".jpg", ".jpeg", ".png", ".tif", ".tiff", ".webp", ".html", ".htm"]

ocr:
  default_lang: "spa"       
  pdf_render_dpi: 300

thresholds:
  low: 0.35
  high: 0.65

features:
  enable_visual: true
  enable_text: true
  enable_metadata: true
